// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://olxqeywfuxvkuorztbsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9seHFleXdmdXh2a3Vvcnp0YnNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2Nzg1MDEsImV4cCI6MjA2MTI1NDUwMX0.5xw5vkOXow8cdhbSNSRArlEdhW3BrO2H_ZlyxI1a1Ks";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);